name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build_test_dependency:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: verte-zerg/qrcode-zxing-tests

      - name: Set up Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install conan

      - name: Build
        run: sh build.sh

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: |
            build/Reader
            build/RawReader
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs: build_test_dependency

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-binaries

      - name: Add execute permission to binaries
        run: |
          chmod +x Reader RawReader

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Install dependencies
        run: go get .

      - name: Run tests
        run: go test -v -timeout=100s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...

      - name: Install goveralls
        run: |
          go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github -coverprofile=$GITHUB_WORKSPACE/profile.cov